import { jsPDF } from "jspdf";
import { FileDown } from "lucide-react";
import { EmotionData, Emotion } from "@/hooks/useEmotionDetector";
import { emotionConfig } from "@/lib/emotionConfig";

interface ReportGeneratorProps {
  emotionHistory: EmotionData[];
  isDisabled: boolean;
}

const ReportGenerator = ({ emotionHistory, isDisabled }: ReportGeneratorProps) => {
  const generateReport = () => {
    if (emotionHistory.length === 0) return;

    const doc = new jsPDF();
    
    // Title
    doc.setFontSize(24);
    doc.setTextColor(0, 200, 200);
    doc.text("MindFuse Emotion Report", 20, 30);

    // Date
    doc.setFontSize(12);
    doc.setTextColor(100, 100, 100);
    doc.text(`Generated: ${new Date().toLocaleString()}`, 20, 45);

    // Session Info
    doc.setFontSize(14);
    doc.setTextColor(0, 0, 0);
    doc.text("Session Summary", 20, 65);
    
    doc.setFontSize(10);
    doc.text(`Total Data Points: ${emotionHistory.length}`, 20, 75);
    doc.text(`Session Duration: ${Math.round(emotionHistory.length * 0.5)} seconds`, 20, 85);

    // Calculate emotion distribution
    const counts: Record<Emotion, number> = {
      happy: 0,
      sad: 0,
      angry: 0,
      fearful: 0,
      disgusted: 0,
      surprised: 0,
      neutral: 0,
    };

    emotionHistory.forEach(data => {
      counts[data.emotion]++;
    });

    const total = emotionHistory.length;

    // Emotion Distribution
    doc.setFontSize(14);
    doc.text("Emotion Distribution", 20, 105);

    let yPos = 115;
    Object.entries(counts)
      .sort((a, b) => b[1] - a[1])
      .forEach(([emotion, count]) => {
        if (count > 0) {
          const percentage = Math.round((count / total) * 100);
          const config = emotionConfig[emotion as Emotion];
          doc.setFontSize(10);
          doc.text(`${config.label}: ${percentage}% (${count} occurrences)`, 20, yPos);
          yPos += 10;
        }
      });

    // Dominant Emotion
    const dominantEmotion = Object.entries(counts)
      .sort((a, b) => b[1] - a[1])[0];
    
    doc.setFontSize(14);
    doc.text("Primary Emotion", 20, yPos + 20);
    doc.setFontSize(12);
    doc.text(
      `${emotionConfig[dominantEmotion[0] as Emotion].label} - ${Math.round((dominantEmotion[1] / total) * 100)}%`,
      20,
      yPos + 30
    );

    // Footer
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text("Generated by MindFuse - AI-Powered Emotion Detection", 20, 280);
    doc.text("Built for Hackstrom 2025", 20, 285);

    // Save
    doc.save(`mindfuse-report-${Date.now()}.pdf`);
  };

  return (
    <button
      onClick={generateReport}
      disabled={isDisabled}
      className="btn-primary w-full justify-center disabled:opacity-50 disabled:cursor-not-allowed"
    >
      <FileDown className="w-4 h-4" />
      Download Report (PDF)
    </button>
  );
};

export default ReportGenerator;
